### PR TITLE
Fixed issues with chat box in Safari

### PR DESCRIPTION
**Pull request by elibosley**
# PR fixing chat issues in Safari

## PR Status
**READY**

## Ready for PR?
- [x] I have updated the CHANGELOG with an entry including a description, a link to my profile, and a link to the issue ticket. This change is filed under an Enhancement or Bug Fix, is shown under the relevant release tag name, and is included in my PR branch.
- [x] I have run `lein run-lint` to check for linting errors.

@emilyseibert @oconn @dehli

### CODE REVIEW

**Comment by dehli** [comment]
Did you try previewing a game that you hadn't joined?

**Comment by elibosley** [comment]
@dehli I'm not sure why it says the preview failed - it definitely worked on Netlify haha.

**Comment by dehli** [comment]
This is the error I got on Netlify:

```
10:11:58 AM: java.io.IOException: Cannot run program "node_modules/postcss-cli/bin/postcss" (in directory "/opt/build/repo"): error=2, No such file or directory
at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
java.lang.Runtime.exec (Runtime.java:620)
```

**Comment by elibosley** [comment]
@dehli Ready for review

**Comment by elibosley** [comment]
@dehli Fixed build issues

**Pull request merged**
